name: currency_converter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.0
  get_it: ^8.0.0
  dartz: ^0.10.1
  shared_preferences: ^2.5.4
  sqflite: ^2.3.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  fl_chart: ^0.66.0
  flutter_hooks: ^0.21.3+1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  smooth_page_indicator: ^2.0.1
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter_native_splash:
  android: true
  ios: true
  color: "#2563EB"
  image: assets/images/splash.png
  fullscreen: true
  android_12:
    color: "#2563EB"
    image: assets/images/splash.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  adaptive_icon_background: "#2563EB"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/images/
